using System;
using System.Collections.Generic;

namespace Affine_Cipher
{
    public class LetterConstants
    {
        // Number of letters in the alphabet
        public const int NUM_CHARS = 26;

        public static readonly Dictionary<char,int> LetterToNum = new Dictionary<char,int>
        {
            {'a', 0},
            {'b', 1},
            {'c', 2},
            {'d', 3},
            {'e', 4},
            {'f', 5},
            {'g', 6},
            {'h', 7},
            {'i', 8},
            {'j', 9},
            {'k', 10},
            {'l', 11},
            {'m', 12},
            {'n', 13},
            {'o', 14},
            {'p', 15},
            {'q', 16},
            {'r', 17},
            {'s', 18},
            {'t', 19},
            {'u', 20},
            {'v', 21},
            {'w', 22},
            {'x', 23},
            {'y', 24},
            {'z', 25},
            {'A', 0},
            {'B', 1},
            {'C', 2},
            {'D', 3},
            {'E', 4},
            {'F', 5},
            {'G', 6},
            {'H', 7},
            {'I', 8},
            {'J', 9},
            {'K', 10},
            {'L', 11},
            {'M', 12},
            {'N', 13},
            {'O', 14},
            {'P', 15},
            {'Q', 16},
            {'R', 17},
            {'S', 18},
            {'T', 19},
            {'U', 20},
            {'V', 21},
            {'W', 22},
            {'X', 23},
            {'Y', 24},
            {'Z', 25}           
        };
        public static readonly Dictionary<int, char> NumToLetter = new Dictionary<int, char>
        {
            {0, 'a'},
            {1, 'b'},
            {2, 'c'},
            {3, 'd'},
            {4, 'e'},
            {5, 'f'},
            {6, 'g'},
            {7, 'h'},
            {8, 'i'},
            {9, 'j'},
            {10, 'k'},
            {11, 'l'},
            {12, 'm'},
            {13, 'n'},
            {14, 'o'},
            {15, 'p'},
            {16, 'q'},
            {17, 'r'},
            {18, 's'},
            {19, 't'},
            {20, 'u'},
            {21, 'v'},
            {22, 'w'},
            {23, 'x'},
            {24, 'y'},
            {25, 'z'},
            {26, 'A'},
            {27, 'B'},
            {28, 'C'},
            {29, 'D'},
            {30, 'E'},
            {31, 'F'},
            {32, 'G'},
            {33, 'H'},
            {34, 'I'},
            {35, 'J'},
            {36, 'K'},
            {37, 'L'},
            {38, 'M'},
            {39, 'N'},
            {40, 'O'},
            {41, 'P'},
            {42, 'Q'},
            {43, 'R'},
            {44, 'S'},
            {45, 'T'},
            {46, 'U'},
            {47, 'V'},
            {48, 'W'},
            {49, 'X'},
            {50, 'Y'},
            {51, 'Z'}           
        };
    }
}